table agg_stars_compliance
	lineageTag: d5000005-0001-0001-0001-00000000002d00
	sourceLineageTag: [dbo].[agg_stars_compliance]

	measure 'Avg Stars Compliance' = AVERAGE(agg_stars_compliance[compliance_pct])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d5000005-0001-0001-0001-00000000002de1

	column measure_id
		dataType: string
		lineageTag: d5000005-0001-0001-0001-00000000002d01
		summarizeBy: none
		sourceColumn: measure_id

		annotation SummarizationSetBy = Automatic

	column plan_year
		dataType: int64
		formatString: 0
		lineageTag: d5000005-0001-0001-0001-00000000002d02
		summarizeBy: sum
		sourceColumn: plan_year

		annotation SummarizationSetBy = Automatic

	column lob
		dataType: string
		lineageTag: d5000005-0001-0001-0001-00000000002d03
		summarizeBy: none
		sourceColumn: lob

		annotation SummarizationSetBy = Automatic

	column denominator
		dataType: int64
		formatString: 0
		lineageTag: d5000005-0001-0001-0001-00000000002d04
		summarizeBy: sum
		sourceColumn: denominator

		annotation SummarizationSetBy = Automatic

	column numerator
		dataType: int64
		formatString: 0
		lineageTag: d5000005-0001-0001-0001-00000000002d05
		summarizeBy: sum
		sourceColumn: numerator

		annotation SummarizationSetBy = Automatic

	column compliance_pct
		dataType: double
		lineageTag: d5000005-0001-0001-0001-00000000002d06
		summarizeBy: sum
		sourceColumn: compliance_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition agg_stars_compliance = entity
		mode: directLake
		source
			entityName: agg_stars_compliance
			expressionSource: 'DirectLake - lh_gold_curated'
