table agg_pa_tat
	lineageTag: d5000005-0001-0001-0001-00000000002c00
	sourceLineageTag: [dbo].[agg_pa_tat]

	measure 'Avg PA TAT (Median Hrs)' = AVERAGE(agg_pa_tat[tat_median_hrs])
		lineageTag: d5000005-0001-0001-0001-00000000002ce1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg PA SLA Compliance' = AVERAGE(agg_pa_tat[sla_compliance_pct]) 
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d5000005-0001-0001-0001-00000000002ce2

	column payer_id
		dataType: string
		lineageTag: d5000005-0001-0001-0001-00000000002c01
		summarizeBy: none
		sourceColumn: payer_id

		annotation SummarizationSetBy = Automatic

	column plan_year
		dataType: int64
		formatString: 0
		lineageTag: d5000005-0001-0001-0001-00000000002c02
		summarizeBy: sum
		sourceColumn: plan_year

		annotation SummarizationSetBy = Automatic

	column request_type
		dataType: string
		lineageTag: d5000005-0001-0001-0001-00000000002c03
		summarizeBy: none
		sourceColumn: request_type

		annotation SummarizationSetBy = Automatic

	column pa_count
		dataType: int64
		formatString: 0
		lineageTag: d5000005-0001-0001-0001-00000000002c04
		summarizeBy: sum
		sourceColumn: pa_count

		annotation SummarizationSetBy = Automatic

	column tat_median_hrs
		dataType: double
		lineageTag: d5000005-0001-0001-0001-00000000002c05
		summarizeBy: sum
		sourceColumn: tat_median_hrs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tat_p95_hrs
		dataType: double
		lineageTag: d5000005-0001-0001-0001-00000000002c06
		summarizeBy: sum
		sourceColumn: tat_p95_hrs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sla_compliance_pct
		dataType: double
		lineageTag: d5000005-0001-0001-0001-00000000002c07
		summarizeBy: sum
		sourceColumn: sla_compliance_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition agg_pa_tat = entity
		mode: directLake
		source
			entityName: agg_pa_tat
			expressionSource: 'DirectLake - lh_gold_curated'
